image: archlinux
packages:
  - git
  - namcap
  - python-aioopenssl
  - python-aiosasl
  - python-orderedset
  - python-sortedcollections
  - python2-sortedcontainers
  - nodejs-less-plugin-clean-css
sources:
  - https://git.sr.ht/~samwhited/pkgbuilds
tasks:
  - lint: |
      find pkgbuilds/ -name PKGBUILD -print0 | xargs -0 -n1 namcap
  - build: |
      cd pkgbuilds/
      for f in *; do pushd $f; makepkg -s --noprogressbar --nocheck --noconfirm; popd; done
  - check: |
      find pkgbuilds/ -name '*.pkg.tar.xz' -print0 | xargs -0 -n1 namcap
