image: archlinux
packages:
  - git
  - namcap
sources:
  - https://git.sr.ht/~samwhited/pkgbuilds
tasks:
  - lint: |
      find pkgbuilds/ -name PKGBUILD -print0 | xargs -0 -n1 namcap
  - build: |
      cd pkgbuilds/
      for f in *; do pushd $f; yes y | makepkg -is --noprogressbar --nocheck; popd; done
  - check: |
      find pkgbuilds/ -name '*.pkg.tar.xz' -print0 | xargs -0 -n1 namcap
