image: archlinux
packages:
  - git
  - namcap
sources:
  - https://git.sr.ht/~samwhited/pkgbuilds
tasks:
  - lint: |
      find pkgbuilds/ -name PKGBUILD -execdir namcap \{\} \;
  - build: |
      find pkgbuilds/ -name PKGBUILD -execdir makepkg -is --noprogressbar \{\} \;
  - check: |
      find pkgbuilds/ -name '*.pkg.tar.xz' -execdir namcap \{\} \;
